mutation InsertPageContent($contentHtml: String!, $path: String!, $lastUpdated: Timestamp!, $metaDescription: String, $pageTitle: String, $scriptsJs: String, $stylesCss: String) @auth(level: USER) {
  pageContent_insert(data: {contentHtml: $contentHtml, path: $path, lastUpdated: $lastUpdated, metaDescription: $metaDescription, pageTitle: $pageTitle, scriptsJs: $scriptsJs, stylesCss: $stylesCss})
}

query GetPageContentByPath($path: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  pageContents(where: {path: {eq: $path}}) {
    id
    contentHtml
    lastUpdated
    metaDescription
    pageTitle
    path
    scriptsJs
    stylesCss
  }
}

mutation UpdatePageContent($id: UUID!, $contentHtml: String, $lastUpdated: Timestamp, $metaDescription: String, $pageTitle: String, $path: String, $scriptsJs: String, $stylesCss: String) @auth(level: USER) {
  pageContent_update(id: $id, data: {contentHtml: $contentHtml, lastUpdated: $lastUpdated, metaDescription: $metaDescription, pageTitle: $pageTitle, path: $path, scriptsJs: $scriptsJs, stylesCss: $stylesCss})
}

mutation DeletePageContent($id: UUID!) @auth(level: USER) {
  pageContent_delete(id: $id)
}